nix-community/disko

- lib/default.nix
- tests/test.nix
This feels slightly cleaner and makes the code shorter.
> use findmnt and mount with X-mount.mkdir

- example/raid.nix
- lib/default.nix
- tests/test.nix
> add mdadm support

- lib/default.nix
This allows us to create a lv with size 100%FREE for all the availeable
size of the VG, etc.
> Support logical volume sizing in logical extents units

- example/tmpfs.nix
- tests/tmpfs.nix
- types.nix
we could also have tmpfs as toplevel instead of nodev. but I guess we also want to have unionfs and bindfs or something at some point? maybe even nfs?
> add tmpfs support

- cli.nix
> pass lib along

- example/zfs.nix
- tests/cli.nix
- tests/complex.nix
- tests/lib.nix
- tests/luks-lvm.nix
- tests/module.nix
- tests/zfs.nix
> tests: change passphrase to secretsecret

- flake.lock
- flake.nix
- linux-testing-bcachefs.nix
- tests/bcachefs.nix
> Bcachefs fixes

- docs/quickstart.md
> quickstart: fix example

- types/filesystem.nix
- types/nodev.nix
fixes https://github.com/nix-community/disko/issues/169
> filesystem/nodev: mountpoint can be empty

- linux-testing-bcachefs.nix
> linux-bcachefs: 6.1.0-2023-02-01 -> 6.2.0-2023-03-13

- types/table.nix
> table: fix mounting devices

- linux-testing-bcachefs.nix
> linux-bcachefs-testing: 6.2.0-2023-03-22 -> 6.2.0-2023-04-15

- docs/quickstart.md
> quickstart: fix grammar

- docs/upgrade-guide.md
Without headline it is harder to follow the upgrade guide
> Add missing headline in upgrade-guide.md

- bors.toml
- example/lvm-sizes-sort.nix
- linux-testing-bcachefs.nix
- tests/lvm-sizes-sort.nix
- types/lvm_vg.nix
- types/table.nix
- types/zfs_fs.nix
- types/zpool.nix
https://github.com/nix-community/disko/issues/195
> types/lvm: create lv with 100% size last

- disko
> disko cli: allow mode to be disko

- lib/types/btrfs.nix
- tests/btrfs-subvolumes.nix
should fix https://github.com/nix-community/disko/pull/248#issuecomment-1575341938
I expected conatMapAttrs to merge deeply, sadly the test didn't catch that before since the test subvolume (because it's the last one) was accidentally created.
> btrfs: create all subvolumes

- README.md
- docs/HowTo.md
- docs/INDEX.md
- docs/quickstart.md
- docs/reference.md
- docs/requirements.md
- docs/supportmatrix.md
Changed the README as per the Coda version, but created embryo How To and Reference Guides containing content that had been created in this repo since the Coda document was created. Changed the Coda version slightly to refer to it. The Reference and How To still need editing and new content.
> Changes to documentation: Jill

- cli.nix
- default.nix
- module.nix
fix https://github.com/nix-community/disko/issues/279
> diskoNoDeps -> diskoScriptNoDeps

- example/btrfs-subvolumes.nix
- example/complex.nix
- example/gpt-bios-compat.nix
- lib/default.nix
- lib/types/btrfs.nix
- lib/types/disk.nix
- lib/types/filesystem.nix
- lib/types/gpt.nix
- lib/types/luks.nix
- lib/types/lvm_pv.nix
- lib/types/lvm_vg.nix
- lib/types/mdadm.nix
- lib/types/mdraid.nix
- lib/types/nodev.nix
- lib/types/swap.nix
- lib/types/table.nix
- lib/types/zfs.nix
- lib/types/zfs_fs.nix
- lib/types/zfs_volume.nix
- lib/types/zpool.nix
refactor some things, to make the code (hopefully) easier to understand.
> lib.types: turn _create, _mount and _config into values

- lib/default.nix
- lib/make-disk-image.nix
- lib/tests.nix
- lib/types/disk.nix
- lib/types/mdadm.nix
- tests/bcachefs.nix
- tests/boot-raid1.nix
- tests/btrfs-subvolumes.nix
- tests/cli.nix
- tests/complex.nix
- tests/default.nix
- tests/gpt-bios-compat.nix
- tests/hybrid-tmpfs-on-root.nix
- tests/hybrid.nix
- tests/legacy-table.nix
- tests/luks-btrfs-subvolumes.nix
- tests/luks-lvm.nix
- tests/lvm-raid.nix
- tests/lvm-sizes-sort.nix
- tests/make-disk-image.nix
- tests/mdadm.nix
- tests/module.nix
- tests/multi-device-no-deps.nix
- tests/negative-size.nix
- tests/simple-efi.nix
- tests/swap.nix
- tests/tmpfs.nix
- tests/with-lib.nix
- tests/zfs-over-legacy.nix
- tests/zfs.nix
like make-disk-image.nix from nixpkgs, but cooler :)
(multi image support, takes disko config, etc.)
> add image builder based on disko

- README.md
> capitalise NixOS

- .mergify.yml
- lib/tests.nix
- tests/cli.nix
- tests/complex.nix
- tests/module.nix
- tests/zfs-over-legacy.nix
- tests/zfs.nix
This will conflict with the user defaults otherwise
> do not set networking.hostId in vm tests by default

- disko
fixes use with the experimental option "no-url-literals"
> fix: unquoted flake ref

- example/boot-raid1.nix
> boot -> BOOT for change of order

- example/bcachefs.nix
- example/btrfs-subvolumes.nix
- example/complex.nix
- example/legacy-table.nix
This seems to do better alignment
> use M instead MiB suffix everywhere

- example/bcachefs.nix
- example/boot-raid1.nix
- example/legacy-table.nix
- example/luks-interactive-login.nix
- example/luks-lvm.nix
- example/luks-on-mdadm.nix
- example/lvm-raid.nix
- example/lvm-sizes-sort.nix
- example/simple-efi.nix
- example/swap.nix
- example/tmpfs.nix
- example/zfs-over-legacy.nix
100M is not enough and I see people just copying examples without putting in any extra thoughts https://github.com/TUM-DSE/doctor-cluster-config/pull/368
> make boot large enough in tests

- docs/quickstart.md
this should take care of https://github.com/nix-community/disko/issues/429
> quickstart: remove deprecated disk handling

- example/luks-btrfs-subvolumes.nix
- example/luks-interactive-login.nix
- example/luks-lvm.nix
- lib/types/luks.nix
i feel we should better use the nixos options, so when other people want to debug problem they really see what is defined.
> luks: use allowDiscards option

- example/btrfs-subvolumes.nix
- example/luks-btrfs-subvolumes.nix
- lib/default.nix
- lib/types/btrfs.nix
- tests/btrfs-subvolumes.nix
- tests/luks-btrfs-subvolumes.nix
alternative implementation of https://github.com/nix-community/disko/pull/363 with a more minimal interface
> add btrfs swap support

- lib/make-disk-image.nix
This is a follow up to #383 which fixes some of the problems I described there.
I tested most possible combinations and also used --write-to-disk to write to a physical disk and booted it and it worked just fine
> make-disk-image: add features and fix stuff from #383

- docs/reference.md
Just adding some docs for `lib/make-disk-image`
> docs: add make-disk-image

- example/swap.nix
- lib/types/swap.nix
- tests/swap.nix
This requires more code and is not implemented just now.
> swap: don't activate random encrypted swap files

- lib/types/luks.nix
Along with adding flags to cryptsetup open I also unified the two calls to use a single binding, this also fixes an issue with one not using `config.extraFormatArgs` from #304
I added `--persistent` to the open call after format `_create` since that makes sense you'd want to keep those set.
The changes to `keyFileArgs` binding were due to it having a erroneous newline which caused issue when adding any flags after it was used; The `lib.forEach config.additionalKeyFiles` line was relying on that newline, so I put the `cryptsetup luksAddKey` in a string block to add that newline back in.
> luks: apply flags set in `config.settings`

- lib/types/zpool.nix
> zfs: Tolerate no mountable dataset

- example/complex.nix
Related: https://english.stackexchange.com/questions/19653
> example: fix typo

- disko-install
- disko-install.nix
- flake.nix
- install-cli.nix
- tests/disko-install/configuration.nix
- tests/disko-install/default.nix
disko-install combines disko and nixos-install into a single command.
Example usage:
sudo ./disko-install --flake /someflake#eva --disk sda /dev/zvol/zroot/test
> add disko-install command

- lib/types/lvm_vg.nix
> lvm_vg: add priority option

- example/long-device-name.nix
- lib/tests.nix
- lib/types/gpt.nix
- tests/long-device-name.nix
this should mitigate some of the problems in https://github.com/nix-community/disko/issues/551
also we fix the test framework with recent versions of nixpkgs
> types gpt: hash long device names

- lib/types/table.nix
should fix https://github.com/nix-community/disko/issues/573
> types table: fix duplicate create run

- lib/types/gpt.nix
- tests/make-disk-image.nix
this should fix couple of bugs and should make it easier to migrate from the legacy table to the new gpt table.
> idempotent gpt

- install-cli.nix
> disko-install: simplify let statements

- docs/reference.md
> Fix typo in reference.md

- lib/make-disk-image.nix
Fixes https://github.com/nix-community/disko/commit/8a4585a200aeec1afdc32bd0d495e26b66d828ca for me.
> Fix xargs command not found in make-disk-image script

- module.nix
Fixes https://github.com/nix-community/disko/pull/640#discussion_r1609401410
> module: fix typo pkgs -> lib

- docs/table-to-gpt.md
- Generalize examples to be independent of ZFS
- Reduce indent of examples to focus on the relevant bits
- Add explicit migration steps, pre- and postconditions
> Update table-to-gpt migration guide

- README.md
Fixed a typo in the documentation.
> fix(docs): fixed typo in README.md

- lib/default.nix
> fix option type in `mkHook`

- example/f2fs.nix
- lib/types/filesystem.nix
- tests/f2fs.nix
> f2fs: init

- module.nix
> module: fix options.json rendering again

- module.nix
> Fix the manual by fixing string escape

- lib/make-disk-image.nix
> make-disk-image: automatically add ZFS to kernel

- docs/disko-images.md
- lib/make-disk-image.nix
> docs: rename `vdb` -> `main`

- docs/interactive-vm.md
- lib/interactive-vm.nix
same as https://github.com/nix-community/disko/pull/792
> interactive-vm: use host pkgs in the launcher script.

- lib/types/lvm_vg.nix
The lvm_type is only set on RAID and thinly provisioned LVM volumes, but regular LVM volumes without a type can also have snapshots.
Ping @Mic92 (not sure why I cannot ask for reviews on this repo)
> Always add dm-snapshot when LVM is used

- docs/disko-install.md
> docs: Fix grammar in offline installer

- docs/disko-install.md
Small typo fix going from "Than" --> "Then"
> Grammar update on disko-install.md

- disko
> disko cli: remove requirement for leading ./

- docs/table-to-gpt.md
Fixes a wrong attribute path in the documentation.
> fix(docs): wrong attr path

- docs/INDEX.md
When I tried using it it was broken, so here's a small fix
> fixed logo suffix in INDEX.md

- cli.nix
Found this while trying to repro #523
> disko cli: fix misleading error message

- lib/default.nix
This is generally regarded as a code-smell. I did utilize `with lib;` in some places where I felt it aided readability, but it's very clearly scoped in those situations.
See https://github.com/nix-community/disko/pull/835#issuecomment-2416126497
> lib: Remove global `with lib;`

- .gitignore
- CONTRIBUTING.md
- README.md
- docs/INDEX.md
- docs/testing.md
> docs: Add docs for contributors

- lib/make-disk-image.nix
> Add kmod to dependencies

- docs/disko-install.md
- tests/disko-install/default.nix
found in https://github.com/nix-community/disko/pull/761
> fix offline installation

- flake.nix
- lib/default.nix
- lib/types/gpt.nix
- lib/types/luks.nix
- lib/types/table.nix
This will be very useful for generating documentation.
Backported from a5c646bd93c956d41d532dce4c8ff95573c3d2a0 for #789
> lib: Fix jsonTypes evaluation

- lib/types/zpool.nix
fixes https://github.com/nix-community/disko/issues/893
> also passthrough rootfs mountoptions

- docs/quickstart.md
Fixes a flaw so minor that's it barely warrants an explanation... :see_no_evil:
> Fix minor typo

- docs/disko-images.md
Add user documentation for https://github.com/nix-community/disko/pull/970.
https://github.com/Thaigersprint/thaigersprint-2025/issues/1
> docs: disko-images: add binfmt section

- lib/types/luks.nix
> UI nit: remove unnecessary newline when prompting user for password

- docs/testing.md
It took me a while to figure out how to debug the project while working on it. Hopefully these additional paragraphs will help future folk when they come to debugging it too.
> Improve testing documentation

- package.nix
this can save us some rebuilds in CI
> use fileset when building disko

- lib/make-disk-image.nix
> make-disk-image: QEUM_OPTS -> QEMU_OPTS
