- lib/default.nix
- tests/test.nix
Some deployments just need a raw block device because the app works better when handling those.
Examples: Ceph, Longhorn, OpenEBS.
The new `noop` type supports that. It just does nothing with the partitions created, whenever applied.
@moduon MT-904
> feat: noop partitions

- lib/default.nix
If the keyfile attribute is not present it will omit any keyfile luks
configuration and instead will make the user be prompted for any
passphrases.
> Support optional keyfile for luks encrypted partitions

- types.nix
> fix: mkfs randomly not detecting just partitioned device

- types.nix
eMMC and SD cards will show up as `/dev/mmcblk0` on most machines and they follow the same partitioning scheme as nvme devices (e.g `/dev/mmcblk0p1`)
> add support for mmc blk devices

- module.nix
for netboot or kexec based installer we may want to avoid uploading too many dependencies because the target could go out-of-memory.
> add disko output variant without package list

- types.nix
Simple little error shellcheck happened to find. If you're trying to get the exit status of `grep` in that command pipe, I believe a command group is intended, not command substitution
> swap: fix typo for checking if swap is on

- example/complex.nix
- example/luks-lvm.nix
- example/lvm-raid.nix
- example/zfs-over-legacy.nix
- types.nix
So the `filesystem.options` option never seemed to actually be used anywhere in disko (for creating, mounting, or configuring) and it seems to have been confused with the `mountOptions` option, which is used but often only during `_mount` and not `_config` (except for `nodev` where it was passed through correctly)
I may be off-base with that observation (still trying to fully figure disko out tbh) but if that observation is correct, this PR removes the `filesystems.options` type and passes through `filesystems.mountOptions` through to the filesystem definitions output by `_config` so that they get propagated to the system config as well
I also had to update the tests which used `filesystem.options` (which did not seem to do anything) in the place of using `filesystem.mountOptions` to …
> types: pass through mountOptions to _config for all types

- example/btrfs-subvolumes.nix
- types.nix
This adds support for specifying separate configuration and mount points for BTRFS subvolumes by implementing them as a new subtype for the `btrfs` type
It sort of follows from the work in #33, but does not use any of that implementation because disko has largely been rewritten since then to use types
I believe I've done everything mostly reasonably (since I copied the patterns LVM and ZFS were using for the most part), but I don't actually fully know what I'm doing, so please let me know if some things should be done differently
I've tested this by installing my new laptop from my config (see the disko config [here](https://github.com/lilyinstarlight/foosteros/blob/e52af84684ca462ccc8f8e57a5cdd5c3a818407b/hosts/bina/hardware-configuration.nix#L62-L134)) and via the flake checks in disko …
> types: add btrfs_subvol type

- module.nix
- types.nix
This PR fixes the missing descriptions in disko which is used by ExpidusOS by default. This will get rid of these errors.
```
options.json> error: option disko.devices has no description
options.json> error: option disko.devices.disk has no description
options.json> error: option disko.devices.disk.<name>.content has no description
options.json> error: option disko.devices.disk.<name>.device has no description
options.json> error: option disko.devices.disk.<name>.name has no description
options.json> error: option disko.devices.lvm_vg has no description
options.json> error: option disko.devices.lvm_vg.<name>.lvs has no description
options.json> error: option disko.devices.lvm_vg.<name>.lvs.<name>.content has no description
options.json> error: option …
```
> feat: add the descriptions for the options

- .github/workflows/update-flake-lock.yml
This reverts commit c681875a0c17f6e7baf4f398809be3790189be1c.
That did not quite work, but now we have our own bot for disko.
> Revert "don't use bot token for flake updates"

- .github/workflows/update-flake-lock.yml
v19 of the action has a default token that works well
> ci: remove unneeded github token

- ci.nix
- cli.nix
- default.nix
- doc.nix
- example/with-lib.nix
- flake.nix
- linux-testing-bcachefs.nix
- module.nix
- tests/default.nix
- tests/lib.nix
- types/btrfs.nix
- types/btrfs_subvol.nix
- types/default.nix
- types/disk.nix
- types/luks.nix
- types/lvm_lv.nix
- types/lvm_vg.nix
- types/mdadm.nix
- types/nodev.nix
- types/partition.nix
- types/swap.nix
- types/zfs_dataset.nix
- types/zpool.nix
Perhaps a bit controversial, and a bit subjective, so please feel free to shoot down if it doesn't align with the maintainers point of view.
I'm a big fan of the [black] style of formatting; 
> _Black_ is the uncompromising Python code formatter. By using it, you agree to cede
> control over minutiae of hand-formatting. In return, _Black_ gives you speed,
> determinism, and freedom from `pycodestyle` nagging about formatting. You will save time
> and mental energy for more important matters.
> 
> Blackened code looks the same regardless of the project you're reading. Formatting
> becomes transparent after a while and you can focus on the content instead.
> 
> _Black_ makes code review faster by producing the smallest diffs possible.
`statix` goes a little further by normalising some …
> Standardise formatting with nixpkgs-fmt and some patterns with statix 

- types/default.nix
Currently creating an mdadm raid fails for me as it tries to create a filesystem on /dev/md/raidp1 device, which does not exist. This fixes that since /dev/md/raid1 exists instead.
> fix mdadm raid device numbering style

- default.nix
- doc.nix
- example/boot-raid1.nix
- example/btrfs-subvolumes.nix
- example/config.nix
- example/gpt-bios-compat.nix
- example/hybrid.nix
- example/mdadm.nix
- example/stand-alone/configuration.nix
- example/with-lib.nix
- flake.nix
- module.nix
- statix.toml
- tests/bcachefs.nix
- tests/default.nix
- tests/lib.nix
- types/default.nix
- types/lvm_vg.nix
- types/nodev.nix
- types/swap.nix
Following on from #143 
> We can merge them with the inherits and can try to configure the formater later
Awesome! Thanks for being flexible. I can be on the fence about the inherit fixes myself. Looks easy to disable, but it appears there are two variants to that check;
```
W03 manual_inherit
W04 manual_inherit_from
```
<details>
<summary>(Probably uninteresting detail on the difference here)</summary>
The former being cases like;
```
[W03] Warning: Assignment instead of inherit
╭─[<stdin>:18:3]
│
18 │   types = types;
·   ───────┬──────
·          ╰──────── This assignment is better written with inherit
────╯
```
the latter being;
```
[W04] Warning: Assignment instead of inherit from
╭─[./types/lvm_vg.nix:45:11]
│
45 │           fs = lvMounts.fs;
·           ────────┬────────
· …
```
> style: Add config for style normalisation and re-apply

- BREAKING_CHANGES.md
- default.nix
- example/btrfs-subvolumes.nix
- module.nix
- tests/default.nix
- tests/lib.nix
- types/btrfs.nix
- types/btrfs_subvol.nix
- types/default.nix
- types/filesystem.nix
- types/lvm_lv.nix
- types/lvm_pv.nix
- types/lvm_vg.nix
- types/mdadm.nix
- types/mdraid.nix
- types/zfs.nix
- types/zpool.nix
This is a draft because most generated scripts do not pass shellcheck and I want to make sure this approach is reasonable before fixing (or silencing) all of the little nits this finds
I had originally implemented it as a check run in the VM since that is a much simpler change, but I figured people may want to opt-in to having their scripts checked as they are generated (and also it is easier to get errors and fix that way when it's implemented as a checkPhase to the derivation rather than run in a VM way down the line)
(Also I may still change this approach -- I only wrote this in the last hour or two and tend to change my mind after a first implementation, but feedback is very welcome)
> types,module,tests: run shellcheck on scripts before running them in NixOS tests

- tests/bcachefs.nix
- tests/boot-raid1.nix
- tests/btrfs-subvolumes.nix
- tests/cli.nix
- tests/complex.nix
- tests/gpt-bios-compat.nix
- tests/hybrid-tmpfs-on-root.nix
- tests/hybrid.nix
- tests/lib.nix
- tests/luks-lvm.nix
- tests/lvm-raid.nix
- tests/mdadm.nix
- tests/module.nix
- tests/multi-device-no-deps.nix
- tests/negative-size.nix
- tests/simple-efi.nix
- tests/swap.nix
- tests/tmpfs.nix
- tests/with-lib.nix
- tests/zfs-over-legacy.nix
- tests/zfs.nix
Having to piece together which `vm-test-run-disko> [...]` is which test when running `nix flake check -vL` was getting a little annyoing 😄
So this makes them all have distinct names so when they are interleaved in Nix output, it's possible to tell them apart
Let me know if having names on the disko tests is undesired for any reason
> tests: add test names

- tests/cli.nix
- tests/complex.nix
- tests/luks-lvm.nix
- tests/module.nix
- tests/zfs.nix
Related to #108, this fixes `wait_for_text` calls to match against both the old stage-1 and systemd-initrd console prompts for passphrases
It'll be needed later if we intend to enable systemd-initrd on some tests or do a test matrix with it both on+off
> tests: adjust wait_for_text calls to work for systemd-initrd or old stage-1

- types/lvm_vg.nix
the error was
```
error: attribute 'fs' missing
at /nix/store/1s8vxpcqla8hcch7dn3h1lg0b5hf515p-disko/share/disko/types/lvm_vg.nix:47:16:
46|           '';
47|           fs = lvMounts.fs;
|                ^
48|         };
(use '--show-trace' to show detailed location information)
```
> lvm_vg: allow putting unmounted disks into lvm

- disko
With `--arg`, the value is a Nix expression, so for `rootMountPoint` to be a string. its value must be passed with quotes:
```
--root-mountpoint '"/path/to/mnt"'
```
`--argstr` ensures the value can only be a string. `--root-mountpoint /path/to/mnt` will work.
If expecting a Nix expression adds some desired flexibility, I would update the usage to clarify it.
> fix(cli): pass --root-mountpoint value as string

- example/zfs.nix
- tests/zfs.nix
Note that we currently need to hardcode the pool name as it isn't exposed correctly for the subshells atm.
> zfs: add tests for hooks

- README.md
It seems the type is not needed anymore.
> Improve example code in README

- types/zpool.nix
Otherwise creating and mounting the zpool in a live image removes the root disk of the live image.
Tested on physical hardware.
> zpool: add option to mount zpool not at /

- types/zfs_fs.nix
- types/zpool.nix
This is necessary to support non-legacy mounts, since the creation order and the required mounting order can be different in order to not shadow any datasets (see #141).
Adding `-l` to the import statement is also necessary to allow encrypted datasets to be mounted later using disko-mount.
> zpool: don't mount created datasets directly; and fix encrypted import

- types/default.nix
> Add support for /dev/mapper LVM partitions in deviceNumbering

- types/luks.nix
I don't know whether this is a desired feature, so I've opened this PR mostly to stimulate a discussion. I'm happy to change the option name, or even just maintain a simple fork if this is undesirable.
Related to #192. Quoting my particular use case from that issue:
> I have a setup where I have a root disk that is just plain btrfs on a smaller SSD. I then have a data drive that is larger, and LUKS encrypted.
>
> Because Disko automatically adds an initrd.luks.devices entry, I'm prompted for a passphrase on every boot. In reality, I don't need that drive to be unlocked at the initrd phase, and normally just have an /etc/crypttab file that specifies a key file. I'd like to be able to specify an encrypted drive that doesn't end up requiring unlocking during the initrd part of the boot.
This …
> luks: add initrdUnlock option to luks type

- lib/default.nix
This style is used in the xen hypervisor
```sh
$ lsblk
lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
xvda    202:0    0   40G  0 disk
├─xvda1 202:1    0  200M  0 part /boot
└─xvda2 202:2    0 39.8G  0 part /nix/store
/
```
> types: add support for /dev/xvd[a-z] style disks

- example/simple-efi.nix
- lib/default.nix
- lib/types/btrfs.nix
- lib/types/disk.nix
- lib/types/filesystem.nix
- lib/types/gpt.nix
- lib/types/luks.nix
- lib/types/lvm_pv.nix
- lib/types/lvm_vg.nix
- lib/types/mdadm.nix
- lib/types/mdraid.nix
- lib/types/swap.nix
- lib/types/table.nix
- lib/types/zfs.nix
- lib/types/zfs_fs.nix
- lib/types/zfs_volume.nix
- lib/types/zpool.nix
- tests/lib.nix
we also add a new way to reference the parent node in the subtypes, this will be used in the future to simplify the code a bit (since we can pass device directly into an option instead of passing it to the _create, _mount and _config functions. this will also turn these into strings instead of functions, preparing the way for partial applications.
Also this new type uses partlabels instead of deviceNames, getting rid of the deviceNumbering logic we use in the other tables. This would also grant the ability to read the device during runtime from the environment.
> introduce new table_gpt type

- flake.nix
If there is only one module that is getting exported, the convention is
to use that "default" value as the name.
> flake: expose the module as nixosModules.default

- disko
The script is generated by calling `nix-build` on the `cli.nix` file. This fails on systems, which have the nix option pure_eval set, as nix refuses to evaluate an untracked file. This would normally be impure, but in this case the file is supplied in the same nix store path, i.e. it's not referencing foreign files. Thus adding the `--impure` argument should leave the nix call in fact still pure.
> disko cli: fix error about impurity with nix

- example/swap.nix
- lib/types/swap.nix
Quickly drafted idea, this adds a boolean option `resumeDevice` for swap, which sets `boot.resumeDevice` to `dev` when set to true.
Related issue: #277
> feat(swap): add resumeDevice option which sets boot.resumeDevice

- example/complex.nix
- example/luks-lvm.nix
- lib/types/luks.nix
This mirrors the NixOS boot.initrd.luks.devices.<name>.keyFileOffset and boot.initrd.luks.devices.<name>.keyFileSize options.
> feat(luks): Add settings submodule

- example/complex.nix
- example/luks-lvm.nix
- lib/types/luks.nix
- tests/lib.nix
Currently disko allow only a single keyfile. I add an additional option to specify more key files. 
Hint: Separate option of the first key has the benefit to get the possible of passphrase + keyfile for an luks volume.
> Luks add additionalKeyFiles option

- lib/types/luks.nix
Using `keyFileOffset`/`keyFileSize` leads to a `cannot coerce an integer to a string` error. Since they are used to generate the `cryptsetup` command in a script as text, they need to be converted to a string.
> fix(luks): type error with keyfile size/offset

- example/complex.nix
This adds `keyFileOffset` and `keyFileSize` options in `example/complex.nix`. It follows the discussion in #301.
I thought that adding a new example file for these options was a lot of noise for little result. 
@Lassulus if you meant something else with "a new test", please put me on tracks, as I quickly checked the `tests` folder and couldn't think about something relevant I could add there.
> docs(luks): add an example using keyFile options

- lib/types/table.nix
In the `formatScript`, the partition fs-type was specified twice on partition creation when the msdos partition table type is used. Fix this to only be specified once.
A minimal error-reproducing configuration:
```nix
{
disko.devices.disk.disk0 = {
device = "/dev/mmcblk0";
type = "disk";
content = {
type = "table";
format = "msdos";
partitions = [{
fs-type = "fat32";
start = "1MiB";
end = "512MiB";
}];
};
};
}
```
Produces the following format script:
```bash
#! /nix/store/hjala5j03vxhkj6rvgj8kdigm1yrw0p4-bash-5.1-p16/bin/bash
export PATH=/nix/store/2bif24ymzcfb1kdr746yxxi199wlng0w-jq-1.6-bin/bin:/nix/store/mdyd76bv92zx74k7zvihaypwycfdgz1j-parted-3.5/bin:/nix/store/ywygk5zd365clas5im16vv7zcg9nyvd2-systemd-minimal-251.7/bin:$PATH
set -efux
disko_devices_dir=$(mktemp -d)
trap 'rm -rf …
```
> Fix msdos partition table creation

- docs/upgrade-guide.md
- example/btrfs-subvolumes.nix
- lib/types/btrfs.nix
- tests/btrfs-subvolumes.nix
This option allows the creation of subvolumes which won't be mounted, allowing to create more complex btrfs layouts.
This is a personal attempt to fix the issue #288, since it didn't seem to get much attention.
> feat(btrfs): support unmounted subvolumes

- lib/default.nix
This PR adds 2 missing deps for destroyScript:
- `jq`: Unlike other scripts, destroyScript wasn't pulling in `${lib.makeBinPath (cfg.config._packages pkgs)`
- `bash`: destroyScript already uses bash for its shebang but it looks like wipefs also need bash in the PATH
> Added missing dependency to destroyScript

- example/luks-btrfs-subvolumes.nix
- example/luks-interactive-login.nix
- lib/types/luks.nix
- tests/luks-interactive-login.nix
I run the checks with the following patch, because otherwise it wasn't working (see https://github.com/nix-community/disko/issues/321)
```diff
diff --git a/flake.nix b/flake.nix
index 561a847..3d9ca74 100644
--- a/flake.nix
+++ b/flake.nix
@@ -28,14 +28,14 @@
in
{
disko = pkgs.callPackage ./package.nix { };
-          disko-doc = pkgs.callPackage ./doc.nix { };
+          # disko-doc = pkgs.callPackage ./doc.nix { };
default = self.packages.${system}.disko;
});
-      checks = forAllSystems (system:
+      checks.x86_64-linux =
let
-          pkgs = nixpkgs.legacyPackages.${system};
+          pkgs = nixpkgs.legacyPackages.x86_64-linux;
nixosTests = import ./tests {
inherit pkgs;
makeTest = import (pkgs.path + "/nixos/tests/make-test-python.nix");
@@ -47,7 +47,7 @@
touch $out
'';
in
- …
```
> Rename keyFile to passwordFile and dedeprecate

- example/mdadm-raid0.nix
- lib/make-disk-image.nix
- lib/types/gpt.nix
- lib/types/mdadm.nix
- lib/types/zfs_volume.nix
- tests/mdadm-raid0.nix
tests with nix-build were broken, so adding parted where partprobe is used fixes that
we also add a test for raid0, which failed earlier today due to not being removed by the disk-deactvate script
> some small fixups

- lib/types/gpt.nix
The following command:
`sgdisk --new=4:0:-0 /dev/xda`
will work but unless the overall disk size is aligned to 4k, the new partition will not be aligned to 4k.
`--set-alignment=2048 --align-end` aligns new partitions to 1 MiB (2048 sectors). This enables for example `--sector-size=4096` for `cryptsetup luksFormat`.
> Specify alignment for sgdisk.

- lib/types/swap.nix
The `swap` type doesn't have `extraArgs` like for example `btrfs` / `filesystem` type has. I tested it with `[ "-f" "--label=abc" ]` and it works well.
> Add extra args into swap.

- disko
`disko` sets `set -u`. If the user forgets to set the flake attr (e.g. because the useage string doesn't suggest so), then an unbound error is raised.
- default to nothing if unbound
- fix the usage string
> fix: unbound variables are forbidden

- lib/types/luks.nix
Changing how to open encrypted partition from `luksOpen` to `open`.
`open` works same as `luksOpen` for LUKS1/2 but it is more flexible so it is possible to pass `--type=plain`.
I tested it with both LUKS2 and plain encrypted partitions in a single file.
> Changing how to open LUKS.

- lib/types/gpt.nix
- lib/types/mdadm.nix
- lib/types/table.nix
- lib/types/zfs_volume.nix
partprobe without `[DEVICE]` probes all _devices_ and thus those devices can have external effects.
One such external effect is, for example, the following error that had been observed when using a usb live stick device (potentially damaged or otherwise not entirely appropriatly set up).
```console
Error: Partition(s) 1 on /dev/sda have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
```
- Strictly specify the `[DEVICE]` in scope where possible
```console
disko on  fix/external-effects-on-partprobe took 2m55s
❯ rg 'partprobe'
lib/make-disk-image.nix
21:    parted # for partprobe
46:    partprobe
lib/types/mdadm.nix
45: …
```
> fix: avoid external probing effects from other devices

- lib/types/zfs_volume.nix
This fixes a race condition where the partprobe command tries to read the /dev/zvol symlink, potentially before it's created
> zfs_volume: fix /dev/zvol/ symlink race

- lib/make-disk-image.nix
This small change allows to have secrets the nixos config might depend upon, for example you could now do something like this: 
```bash
sudo ./result \
--pre-format-files /tmp/luks.key /tmp/secret.key \
--post-format-files /etc/secureboot/files.db /etc/secureboot/files.db \
--post-format-files /etc/secureboot/GUID /etc/secureboot/GUID \
--post-format-files /etc/secureboot/keys/db/db.key /etc/secureboot/keys/db/db.key \
--post-format-files /etc/ssh/ssh_host_ed25519_key /etc/ssh/ssh_host_ed25519_key \
--post-format-files /etc/ssh/ssh_host_ed25519_key.pub /etc/ssh/ssh_host_ed25519_key.pub \
--post-format-files /etc/ssh/ssh_host_rsa_key /etc/ssh/ssh_host_rsa_key \
--post-format-files /etc/ssh/ssh_host_rsa_key.pub /etc/ssh/ssh_host_rsa_key.pub \
--post-format-files …
```
> make-disk-image: allow secrets-pre-install but after partioning

- lib/types/luks.nix
Before that it was only attempted to unlock luks with the key from `$password`, however that variable didn't exist before.
cc @Lassulus
> luks: fix interactive mount

- module.nix
I do build my workstation with `documentation.nixos.includeAllModules` to also have private modules and external stuff in my local options' reference.
Not sure why exactly this breaks with
error: attribute 'loader' missing
at /nix/store/h6qicay9fgggx9nf6apdl6zkdpdp28xx-source/module.nix:46:19:
45|         type = lib.types.bool;
46|         default = config.boot.loader.systemd-boot.enable || config.boot.loader.grub.efiSupport;
|                   ^
47|       };
but using `defaultText` is the usual fix that also works here.
> module: use defaultText to not depend on the configuration when building the manual

- docs/quickstart.md
It is not necessary to manually set `boot.loader.grub.devices`, since Disko will automatically add the device to this option.
In fact setting the device manually will lead to the following issue, because in `mirroredBoots` the same device will end up twice.
```
error:
Failed assertions:
- You cannot have duplicated devices in mirroredBoots
```
> boot.loader.grub.device not required

- disk-deactivate/disk-deactivate
- disk-deactivate/disk-deactivate.jq
Not sure if `coreutils` needs to be added to `pkgs` somewhere for `dd`, but this should work.
> disk-deactivate: Remove MBR bootstrap code for disk

- lib/types/luks.nix
Use `-r` to avoid mangling backslashes, use `IFS=` to not discard leading and trailing whitespace.
While trying out disko I hit warning SC2162 which caused the build script derivation to fail, because it's ShellChecked. Fix the warning with the suggested approach of combining the `-r` flag and `IFS=`.
> luks: fix read ShellCheck warning SC2162

- example/complex.nix
- lib/default.nix
- tests/complex.nix
These options previously existed but had no effect. Now they are implemented. They only affect mount during disko’s filesystem creation, not during any later mounts.
Adding test case to existing “complex” example and test mostly because couldn’t think of any better place to put it.
> Implement preMountHook & postMountHook

- lib/types/btrfs.nix
Fixes #409
Note: Because existing directories can't be converted to subvolumes directly, this implementation assumes hierarchical subvolume creation order (e.g., `/subvol1` is created before `/subvol1/subvol2`).
> fix: create btrfs subvolume parent directories

- lib/make-disk-image.nix
- module.nix
Sometimes the VM builder can run out of memory and fail to allocate memory when installing the system toplevel, this PR allows this to be adjusted by setting `disko.memSize`
> make-disk-image: make memSize configurable per disk

- lib/types/gpt.nix
This must have accidentally creeped in during a refactor
> lib/types/gpt.nix: default = [] -> default = {}

- lib/make-disk-image.nix
- module.nix
`tests/bcachefs.nix` only works because bcachefs is baked into the kernel, without this PR, disko is not using the same kernel as the nixosConfiguration it is building an image for, which leads to edge cases, such as being able to create a bcachefs but not mount it.
In my testing, I observed that my nixosConfiguration was on kernel 6.7-rc5, whereas Disko's  `make-disk-image.nix` reported kernel 6.1 from `uname -a`, this PR synchronizes everything so that this will never happen.
This kind of thing happened in Nixpkgs with `make-single-disk-zfs-image.nix`, with the same solution
https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/make-single-disk-zfs-image.nix#L224-L228
I've also added an `extraRootModules` to disko's toplevel which allows setting `disko.extraRootModules = [ "zram" ]` …
> make-disk-image: inherit kernel from nixosConfiguration

- lib/make-disk-image.nix
- module.nix
Without this, tools like `f2fs-tools` providing `mkfs.f2fs` for a disko config making an f2fs filesystem won't be possible to pass into the `vmTools` invocation.
> make-disk-image: allow extra dependencies to be passed into image builder

- example/non-root-zfs.nix
- lib/types/zpool.nix
- tests/non-root-zfs.nix
If the zpool's root dataset is not the rootfs and gets mounted on creation, the actual rootfs will get mounted later and shadow the
current mountpoint.
Running `zfs unmount` is the easiest way to unmount the zpool's root dataset on creation without messing up the value of the `mountpoint` setting.
The first commit is a regression test that ensures that the default dataset doesn't get shadowed, which fails without the second commit.
> zpool: fix default dataset getting shadowed

- module.nix
fixes an error when using this minimal configuration:
```nix
let
pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-23.11") { };
disko = fetchTarball "https://github.com/nix-community/disko/tarball/master";
in
pkgs.nixos {
imports = [
"${disko}/module.nix"
"${disko}/example/hybrid.nix"
];
}
```
when running:
```console
$ nix-build
...
error: 'default' at /nix/store/y981rwszq9yi36rvvz2vrr6hb22si0hc-source/lib/default.nix:391:23 called with unexpected argument 'system'
```
> fix broken fallback

- example/non-root-zfs.nix
- lib/types/zfs_fs.nix
- lib/types/zpool.nix
- tests/non-root-zfs.nix
-  tests: check `canmount` ZFS flag is respected
- zpool: only `unmount` when root dataset is mounted
Fixes #486
- zfs: respect `canmount`
Also refactor `zpool` type to use `zfs_fs` to construct the root dataset
for the zpool, which means we no longer need to duplicate the dataset
create and mount logic inside the `zpool` type.
cc @phaer
> zfs: respect `canmount`

- lib/types/gpt.nix
See [the wikipedia article on GUID types][wiki_guid] and the sgdisk man page on `--typecode`.
[wiki_guid]: https://en.wikipedia.org/wiki/GUID_Partition_Table#Partition_type_GUIDs
> lib/types/gpt: accept GUID type to set the partition type

- README.md
Otherwise systemd-boot will refuse to install the bootloader.
> docs: mention EF00 partition type in README.md

- disk-deactivate/disk-deactivate.jq
this is useful in cases where the target machine has a pre-configured RAID setup, as otherwise disko would wipe the partition tables and create new ones but would not be able to inform the kernel about it, as the old raid was still in use.
it's the spiritual successor to #500 ;)
> deactivate: stop raid if disk is a member of it

- lib/types/gpt.nix
On 4Kn disks, 2048-sector alignment is equivalent to 8 MiB which is
excessive. Moreover, there is no point in specifying _any_ alignment
at all because sgdisk defaults to 1 MiB already.
Fixes #497.
> lib/types/gpt: do not hard-code alignment to 2048 sectors

- disk-deactivate/disk-deactivate.jq
- example/hybrid-mbr.nix
- lib/default.nix
- lib/types/gpt.nix
- tests/hybrid-mbr.nix
Since https://github.com/nix-community/disko/pull/168 stalled I decided to rework it to the current status quo.
Changes compared to the previous approach:
- Moved the hybrid mbr code to the gpt module. That is way cleaner than introducing new types imho. The types just make sense when combined with gpt anyway.
- Removed the need for the `gptPartitionNumber` as we now take the index of the list entry.
@oneingan Hope you don't mind.
> Rework Hybrid MBR https://github.com/nix-community/disko/pull/168

- LICENSE
- disk-deactivate/disk-deactivate
See the individual commit messages for details. I ran into this issue while trying to create a custom NixOS installation ISO that can do unattended installs.
> Prevent `disk-deactivate` from failing when `disko` is run in a systemd service

- flake.nix
- lib/types/lvm_vg.nix
The option `disko.devices.lvm_vg.<name>.lvs.<name>.priority` depends on a different option that's unset by default breaking the manual build like this:
… while evaluating the attribute 'optionalValue.value'
at /nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source/lib/modules.nix:856:5:
855|
856|     optionalValue =
|     ^
857|       if isDefined then { value = mergedValue; }
… while evaluating a branch condition
at /nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source/lib/modules.nix:857:7:
856|     optionalValue =
857|       if isDefined then { value = mergedValue; }
|       ^
858|       else {};
(stack trace truncated; use '--show-trace' to show the full trace)
error: The option `disko.devices.lvm_vg.<name>.lvs.<name>.size' is used but not defined.
This is especially noticeable when using …
> Fix manual build

- disko
- disko-install
- install-cli.nix
This seems like a recent addition that we don't have on all NixOS machines.
> disko-install: fix case where lib in NixOS is not defined

- disk-deactivate/disk-deactivate
- example/zfs.nix
- lib/tests.nix
- lib/types/btrfs.nix
- lib/types/filesystem.nix
- lib/types/gpt.nix
- lib/types/luks.nix
- lib/types/lvm_pv.nix
- lib/types/lvm_vg.nix
- lib/types/mdadm.nix
- lib/types/swap.nix
- lib/types/table.nix
- lib/types/zfs_fs.nix
- lib/types/zfs_volume.nix
- lib/types/zpool.nix
rework of https://github.com/nix-community/disko/pull/435 with a smaller (and more logical) scope
> types *: make create idempotent

- lib/types/zpool.nix
fix https://github.com/nix-community/disko/issues/576
Not sure why the device would already have a type though, but it should be safe to continue in case the partition is a zfs member
> types zpool: create pool if device is a zfs_member

- README.md
- docs/quickstart.md
nixos-anywhere is using `disk-config.nix` like described in disko reference documentation.
> docs: unify usage of disk-config.nix

- disk-deactivate/disk-deactivate
- lib/default.nix
gnused is used in the disk-deactivate.jq script, but was not defined in the list of dependencies.
> Add missing dependency gnused

- example/btrfs-only-root-subvolume.nix
- lib/types/btrfs.nix
- tests/btrfs-only-root-subvolume.nix
Hi! Recently when trying to format a btrfs drive I ran into ```syntax error near unexpected token `fi'```.
It looks like #568 introduced a change that generates an empty if statement if neither the swap config or subvolumes are set and this just adds a guard to avoid adding that empty if block if neither are set.
> types btrfs: fix format without swap or subvolumes

- lib/default.nix
The destroy script already has a bash interpreter in use, but when the `disk-deactivate` script is ran, it calls out to /usr/bin/env to query for a bash interpreter. When running the destroyScript in unique places (such as the stage-1 initrd), /usr/bin/env might not exist, so we can make destroyScript more self-contained by reusing the same bash.
> Use existing bash instance when running destroyScript

- disk-deactivate/disk-deactivate.jq
This MR adds more ways to detect disk to deactivate, by using /dev/disk elements. This allows to specify disk paths by /dev/disk/by-id in the config and allow disko to find them when it tries to deactivate them
> Allow more ways to detect disk to deactivate

- docs/reference.md
In the section `### Generating the `.raw` VM Image` in step 3. It is written that the raw image file created is named `vdb`, but in the file [simple-efi.nix](https://github.com/nix-community/disko/blob/a816daa384dd754b7586f51157fc2e1a44e76073/example/simple-efi.nix) the first time `vdb` is mentioned is in `disko.devices.disk` not in `disko.disks` so I assumed that the file [simple-efi.nix](https://github.com/nix-community/disko/blob/a816daa384dd754b7586f51157fc2e1a44e76073/example/simple-efi.nix) was updated it the part about `disko.disks` is a mistake. Otherwise, I would really like to know what I am not understanding here :grin:
> Changed `disko.disks` to `disko.devices.disk`

- example/swap.nix
- lib/types/swap.nix
This just forwards to the underlying NixOS options and expands the mount
script to exhibit the same behavior.
> swap: support swapDevices' discardPolicy and priority options

- lib/types/swap.nix
I.e. instead of effectively ignoring `discardPolicy` when combined with `randomEncryption`, or adding a second option requiring the user to repeat themselves (DRY violation), just enable both when requested via `discardPolicy`.
Without this `discardPolicy` is a NOP when `randomEncryption` is enabled.
Follow-up: #623
> swap: forward discardPolicy option to randomEncryption.allowDiscards

- disko-install
We don't need to keep this env var around for the xargs invocation, only when running `nix-store --load-db`.
> disko-install: only set NIX_STATE_DIR for load-db

- lib/make-disk-image.nix
- module.nix
My use case was compressing disk images, like this:
```nix
disko.extraPostVM = ''
${pkgs.zstd}/bin/zstd --compress $out/*raw
rm $out/*raw
'';
```
> make-disk-image: make extraPostVM configurable from module.nix

- lib/make-disk-image.nix
When building disk images, the VM used to perform partitioning/mkfs inherits the kernel from the nixosConfiguration we're trying to build for. This works fine, until you try to boot a kernel with `zboot`, and in that case you need UEFI to load the image, otherwise you end up with the following log from QEMU:
"unable to handle EFI zboot image with ... compression"
https://github.com/qemu/qemu/blob/master/hw/core/loader.c#L924
Loading OVMF allows us to bypass this issue, and boot the kernel successfully like this:
```
corpo-disko-images> UEFI firmware (version  built at 00:00:00 on Jan  1 1980)
corpo-disko-images> EFI stub: Decompressing Linux Kernel...
corpo-disko-images> EFI stub: Loaded initrd from LINUX_EFI_INITRD_MEDIA_GUID device path
corpo-disko-images> EFI stub: Generating empty DTB …
```
> make-disk-image: use OVMF efi always

- lib/make-disk-image.nix
keeping only `origBuilder` env from host
should resolve https://github.com/nix-community/disko/issues/622
> cleanup host environment passed to VM for image building

- example/lvm-thin.nix
- lib/types/lvm_vg.nix
- tests/lvm-thin.nix
This is #285 rebased with some changes to priority.
- Device mapper kernel modules are loaded based on the LV types used. This applies to all types of LVs (mirror, raid, etc.) that have loadable modules.
- New types for the containing "thin-pool" and nested "thinlv".
- Thin pools have a lower priority than other LVs so that they are created first.
- Example and tests for a setup with thin pool and thin LVs
> lvm_vg: add lvm thinpool/thinlv support 

- lib/types/zpool.nix
if the pool is not imported, zfs list will return a value. So to check that the pool does not exist, we also import it.
fixes https://github.com/nix-community/disko/issues/690
> zfs: try to import zpool in incremental mode

- disko-install
Since we use flakes, channels have no buisness.
This is consistent with nixos-anywhere.
> disko-install: don't copy channel

- example/boot-raid1.nix
- example/gpt-bios-compat.nix
- example/hybrid-tmpfs-on-root.nix
- example/hybrid.nix
- example/luks-on-mdadm.nix
- example/mdadm-raid0.nix
- example/mdadm.nix
- example/with-lib.nix
- lib/types/gpt.nix
Than we no longer need to do this in our examples.
> gpt: move boot partitions to the front of disko

- package.nix
When running disko-install from a distribution that is not NixOS, the nixos-install command was failing due to nixos-install not being in PATH.
Fix the error by adding the nixos-install-tools package to the list of packages passed to lib.makeBinPath.
Fixes #711.
> disko: add nixos-install-tools to PATH

- lib/make-disk-image.nix
- module.nix
I have found this is very necessary when trying to build images for embedded devices like raspberry pi's, in summary:
- make-disk-image: allow vmTools qemu usage to be overriden by disko configuration
This is needed to prevent two layers of emulation when offering a build for a host running binfmt such as an x86 host trying to compile for aarch64 via binfmt
- make-disk-image: allow pkgs to be overriden by disko configuration
This is needed when the nixosConfig you're building for modifies nixpkgs options that lead to evaluation failing unnecessarily
- make-disk-image: allow kernel to be overriden by disko configuration
This is especially useful when trying to build images for embedded systems such as the pi, which have a vendor kernel that can't be booted as part of the disko image …
> make-disk-image: make pkgs, qemu and kernelPackages configurable and overridable

- module.nix
error I got before:
```
… while evaluating the default value of option `disko.imageBuilderKernelPackages`
(stack trace truncated; use '--show-trace' to show the full, detailed trace)
error: attribute 'boot' missing
at /nix/store/g1sd9vgb758mb00vqxcnl9g01f0xgyfb-source/module.nix:38:17:
37|       '';
38|       default = config.boot.kernelPackages;
|                 ^
39|       example = lib.literalExpression "pkgs.linuxPackages_testing";
```
> Fix options.json rendering

- lib/types/zfs_fs.nix
Running `zfs set mountpoint=/mnt/my-ds tank/my-ds`, ZFS may try to unmount the dataset even if the mountpoint didn't change. To avoid the confusing error message, this command is now only run when the mountpoint actually changes.
@Mic92 I'm tagging you as you're the author of #689
> zfs_fs: Fix errors when not changing mountpoint

- lib/interactive-vm.nix
- lib/make-disk-image.nix
- lib/types/disk.nix
When using large image size (1TB for example), vmWithDisko hangs, this PR changes image format to qcow2 to resolve hanging issue.
> Switch to qcow in the interactive VM to avoid hangs when using large image size.

- lib/types/btrfs.nix
- lib/types/swap.nix
Add missing configuration options for regular (types/swap) and btrfs (types/btrfs) swap.
-  `types/swap`: `mountOptions`
- will allow specifying such options as `nofail` which is currently not possible
- named to be consistent with `mountOptions` for other fs types
- relevant mount script changes
- `types/btrfs`:
- `priority` and `options`
- naming consistent with underlying nixos options
> swap: mountOptions; btrfs priority, options

- docs/interactive-vm.md
- lib/default.nix
- lib/interactive-vm.nix
- module.nix
This simplifies the code by making `interactive-vm` a NixOS module rather than a disko module that outputs a NixOS module. By adding the `virtualisation.vmVariantWithDisko` option, this allows the VM to be configured through the NixOS module system:
```nix
{
virtualisation.vmVariantWithDisko = {
virtualisation.fileSystems."/persist" = {
label = "vm-persist";
};
};
}
```
This also allows introspection of the VM's configuration:
```
$ nix repl ~/dotfiles --override-input disko github:Enzime/disko/disko-vm
nix-repl> nixosConfigurations.sigma.config.fileSystems."/persist".label
null
nix-repl> nixosConfigurations.sigma.config.virtualisation.vmVariantWithDisko.virtualisation.fileSystems."/persist".label
"vm-persist"
```
This brings it in line with the existing NixOS VM options …
> Add `virtualisation.vmVariantWithDisko` option

- lib/default.nix
- lib/interactive-vm.nix
- lib/make-disk-image.nix
- lib/types/disk.nix
- module.nix
- tests/make-disk-image-impure.nix
- tests/make-disk-image.nix
As `makeDiskImages` always requires a NixOS configuration, we can simplify the code by converting it into a NixOS module. Then we can make it responsible for populating `system.build.diskoImages` and `system.build.diskoImagesScript`.
> make-disk-image: convert into NixOS module

- lib/types/zfs_fs.nix
- lib/types/zpool.nix
Use `zfs set -u` to update the `mountpoint` flag without mounting or unmounting the filesystem. This flag was added in OpenZFS 2.2.0, which was released October 2023.
The previous logic would not update `mountpoint` if `config.options` was empty or only contained `mountpoint`.
> zfs_fs: support updating mountpoint properly

- module.nix
otherwise documentation depends on the hostname to be set
> imageBuilder: add defaultText

- package.nix
See the commit message for details. Also, you might want to view this PR’s commit with `git show --word-diff`. GitHub’s diff for this commit is kind of hard to read.
> Add binlore for disko and disko-install

- lib/types/lvm_vg.nix
Usually this is added by nixos-generate-config.
However now that we run nixos-generate-config before disko or we even run nixos-facter, we likely not see the LVM block devices anymore.
> lvm: add missing dm-snapshot

- lib/make-disk-image.nix
Quality of life improvement. Forgetting to specify `--build-memory` otherwise leads to long waiting times until the vm runs out of memory and the script fails.
> make-disk-image: use memSize as default build-memory in diskoImagesScript

- README.md
- docs/interactive-vm.md
- flake.nix
- lib/types/zpool.nix
- module.nix
- package.nix
- tests/standalone.nix
I noticed that master is not formatted properly. Would it be interesting to add a CI check for formatting? This PR adds an option to `nix fmt` to check formatting without modifying files which could be added to buildbot.
> Add --check option to formatter in flake

- lib/interactive-vm.nix
Some users will have `boot.zfs.forceImportRoot = false;` in their configurations which conflicts with `boot.zfs.forceImportAll = true;`, so we set it to `true` to match.
> interactive-vm: override `forceImportRoot`

- example/luks-btrfs-raid.nix
- tests/luks-btrfs-raid.nix
Supersedes #802
Fixes #799
I actually feel the example was useful, spreading a btrfs atop two encrypted volumes is not trivial, and while testing I actually discovered that the alphabetical order of the devices matters here, see comment in the code. Not sure if that's something our tests cover yet.
I would've pushed to the original PR but it had the upstream set to master, which I can't push to, even with the "Allow maintainers to edit the PR" flag set.
I've left the original commit intact but can squash if necessary.
> Luks btrfs raid example

- docs/HowTo.md
- docs/disko-install.md
- docs/table-to-gpt.md
- example/bcachefs.nix
- example/btrfs-only-root-subvolume.nix
- example/btrfs-subvolumes.nix
- example/complex.nix
- example/f2fs.nix
- example/hybrid-mbr.nix
- example/hybrid-tmpfs-on-root.nix
- example/hybrid.nix
- example/long-device-name.nix
- example/luks-btrfs-subvolumes.nix
- example/luks-interactive-login.nix
- example/luks-lvm.nix
- example/lvm-sizes-sort.nix
- example/lvm-thin.nix
- example/non-root-zfs.nix
- example/simple-efi.nix
- example/swap.nix
- example/tmpfs.nix
- example/zfs-over-legacy.nix
- example/zfs-with-vdevs.nix
- example/zfs.nix
The alternative would be to do this automatically if format=="vfat" and mountpoint=="/boot", but it's better to be upfront about this.
Fixes #527
> docs: Fix /boot security hole warning in examples

- docs/interactive-vm.md
- lib/interactive-vm.nix
Users might set this value for building images but than need different values when they run interactive virtual machines.
> interactive-vm: allow to override virtualisation.memorySize

- README.md
- disko
- docs/HowTo.md
- docs/disko-images.md
- docs/disko-install.md
- docs/quickstart.md
- flake.nix
- package.nix
- scripts/create-release.nix
- scripts/create-release.sh
- tests/disko-install/default.nix
- version.nix
Fixes #745
This adds a script to create a release. Running it will create two
commits that would appear like this in `git log --oneline`:
67b5fff (master) release: reset released flag
0b808f3 (tag: v1.8.1) release: v1.8.1
100d2f3 docs: last change before release
It also re-creates the `version.nix` file, which is used by the flake
to determine the final version the disko CLI will print.
If `disko --version` is run from exactly the commit tagged `v1.8.1`, it
will print `1.8.1`. If it is run from any commit past that (like
master), it will print `1.8.1-67b5fff`, and if it is run from a local
folder with uncommitted changes, it will print `1.8.1-67b5fff-dirty`.
I decided that the version should always be printed as well. This should make it easy to determine whether users were running an …
> Add version command

- docs/disko-images.md
- lib/make-disk-image.nix
- lib/types/disk.nix
- module.nix
commit1 change extraPostVM type to types.lines.
commit2 add imageName option to disk type.
> options: make extraPostVM mergable.

- disko-install
> disko-install: make output deterministic

- lib/default.nix
Fixes #815
Also a drive-by improvement: The `with lib;` was completely unused, so I removed it.
@yajo FYI. Maybe you could test this again on the hetzner rescue system? I'm fairly confident it will work, but getting confirmation would be great.
> Fix disko using system zfs

- lib/types/gpt.nix
- tests/swap.nix
> swap: fix partition type

- lib/default.nix
because it breaks evaluation on darwin with at least nix 2.18.
Evaluating `lib.splitString "" "foo"` throws the following: `error: invalid regular expression ''`.
You should be able to reproduce by just running `nix flake check` in the disko repository on darwin.
We could avoid that by using lib.stringToCharacters, but as we are mapping over it anyway, lib.stringAsChars seems to be an even better fit.
I tested the examples in hexEscapeUdevSymlinks docstring manually in a nix repl.
> Fix eval on darwin by avoiding calling splitString with an empty string

- example/luks-lvm.nix
- lib/types/lvm_vg.nix
lvcreate -l does not accept a '100%' parameter which currently leads to a crash. THis change automatically changes `100%` to `100%FREE` leading to the intended behavior.
> lvm_vg: fix size=100% leading to crash

- disko-install
I was running into a problem where disko install failed but the logs didn't indicate that.
> UX: be specific if disko-install failed or succeeded

- lib/default.nix
- lib/make-disk-image.nix
- module.nix
Previously, an error like
error: function 'anonymous lambda' called with unexpected argument 'customQemu'
at /nix/store/lbqj1cndic4121whnx8xm0jgb1c8x4xx-source/pkgs/build-support/vm/default.nix:1:1:
was printed when trying to evaluate `config.system.build.vmWithDisko` or `config.system.build.diskoImagesScript` with nixpkgs 24.05 (and below).
Fixes #850
> disk-image: Fix "unexpected argument 'customQemu'" eval error

- flake.nix
- lib/default.nix
- lib/tests.nix
- tests/default.nix
This was recently changed in nixpkgs to be an alias; if nixpkgs is configured to disable aliases, this usage will fail.
> treewide: Fix using pkgs.{build,host}Platform alias

- docs/disko-images.md
Oversight from d106aa7a3d2857e38c6122a32879a9cb158f7d16
> docs: Remove non-existing flag

- docs/disko-install.md
fix: 
```sh
error: flake 'github:nix-community/disko' does not provide attribute `apps.x56_64-linux.disko-install/latest`, `packages.x86_64-linux.disko-install/latest', 'legacyPackages.x86_64-linux.disko-install/latest' or 'disko-install/latest'
```
caused by the previous command
> docs: fix inconsistent disko-install cmd

- README.md
- cli.nix
- default.nix
- disko
- docs/quickstart.md
- docs/reference.md
- lib/default.nix
- lib/make-disk-image.nix
- lib/tests.nix
This adds new outpus like `diskoFormat` and `diskoFormatNoDeps` which are compatible with `nix run` so you can do something like
nix run .#nixosConfigurations.myhostname.config.system.build.diskoFormatNoDeps
as originally intended in #78, or add disko to your configuration like
environment.systemPackages = [
config.system.build.diskoFormat
config.system.build.diskoMount
config.system.build.diskoDisko
];
as mentioned in #454.
The old outputs are marked as deprecated and a warning like this is shown to the user:
```console
trace: evaluation warning: 
The output .mountScript is deprecated in favor of .diskoMount and will be removed in
version 2.0.0! To fix this issue, you need to do the following:
- If you're currently calling "$‍{system.build.mountScript}" as a script,
use …
```
> outputs: make compatible with nix run and package lists

- disko
Fixes regression introduced in daca7be3092f253e5a3c9ce059d5a0225de6902d that would cause the following behavior:
$ ./disko --mode disko --dry-run example/simple-efi.nix
/nix/store/syiv3fhzd7ar2nk5pbh56gswcs4fzvxs-disko/bin/*
Now, it returns the correct script path again:
$ ./disko --mode disko --dry-run example/simple-efi.nix
/nix/store/syiv3fhzd7ar2nk5pbh56gswcs4fzvxs-disko
> cli: Fix legacy aliases

- lib/default.nix
Regression introduced in 94bc0f5bb0dff8b98597f1eb66a7156469932221, because I developed against unstable, which has https://github.com/NixOS/nixpkgs/pull/333744 merged, while 24.05 doesn't.
Partly shellchecks mistake, see https://github.com/koalaman/shellcheck/issues/2891 but whatever, we can't do much more about it than ignore the warning.
Fixes #868
> destroy: Fix shellcheck warning in nixos 24.05

- module.nix
This makes it possible to e.g. run `installTest` for configs that need interactive input. See individual commits for details.
> module: expose tests.bootCommands and tests.enableOCR

- example/zfs-with-vdevs.nix
- lib/tests.nix
- lib/types/zpool.nix
- tests/zfs-with-vdevs.nix
This adds support for the missing categories of devices: `log`, `spare`, and `dedup`.
`log` & `dedup` can each have multiple vdevs assigned (the workload will be load-balanced over these), so these accept a list of vdev configurations. This is actually also true for `special`, but the existing implementation only supported a single vdev. This has been updated to accept either a list of vdevs (like the other two), or a single vdev (for backwards compatibility).
`spare` (like `cache`) just takes a list of device names, neither type supports more complicated vdevs like mirrors.
---
While testing this I ran into a bug that affected all types which support having multiple vdevs (which includes the regular data vdevs). The following topology config:
```nix
{
vdev = [
{
mode = "mirror";
members …
```
> ZFS: Add log, spare & dedup vdev types, support multiple special vdevs, fix bug with mixed vdev types

- lib/default.nix
Apparently nix 2.3 didn't support path interpolations.
> fix: restore nix 2.3 compatibility

- example/gpt-unformatted.nix
- lib/types/gpt.nix
- tests/gpt-unformatted.nix
Since dcabccaad6, if `content` is not specified, it will generate a confusing error "value is null while a set was expected". This changes disko back to its old behaviour in this specific case (i.e. defaulting to 8300 for an unformatted partition).
> Fix evaluation when a GPT partition is left unformatted

- lib/default.nix
- lib/make-disk-image.nix
- module.nix
It seems that there is a difference between how `pkgs` and `lib` get passed to NixOS modules: `pkgs` is the unmodified original, `lib` is the final version after overrides etc.
This causes `pkgs.lib.version` to be `24.11git` in some cases, while `lib.version` is `24.11.20241123.0c58267`.
Maybe this can be fixed in nixpkgs? Either way, this change fixes that issue.
Fixes #904
> make-disk-image: Compare against correct nixpkgs version

- lib/make-disk-image.nix
Fixes #900
This was caused by https://github.com/NixOS/nixpkgs/pull/354535 originally. The breaking changes introduced there have been resolved by https://github.com/NixOS/nixpkgs/pull/360413, but one addition survived, which was the line `source $stdenv/setup`.
Because we used `>` instead of `>>`, `saved-env` was overwritten, so even with the second PR, the script failed with the following error:
/nix/store/pw...ykc-vm-run-stage2: line 16: stdenv: unbound variable
Once this and the second PR mentioned above are merged, #903 will be unblocked.
> disk-image: Fix compatibility with nixpkgs unstable

- disko-install
- lib/make-disk-image.nix
In case we are crossing some filesystem boundary (i.e. /tmp -> /nix/store), this is faster. Also tmpfs might be probelemantic regarding memory usage.
> make-disk-image: create directories images in out path

- lib/types/zfs_volume.nix
This can be useful, for example we can pass `-s` option to create sparse zvol, etc.
> Add extraArgs to zfs_volume.

- example/zfs-with-vdevs.nix
- lib/types/zpool.nix
- tests/zfs-with-vdevs.nix
This is the only way to assign devices rather than fixed gpt partitions. Without reading the code it's not very obvious how disko actually assigns devices to zpools.
> zfs-with-vdevs: add an example for using absolute device paths

- example/xfs-with-quota.nix
- tests/xfs.nix
This PR documents an XFS example that uses the quota feature (`pquota`), based on a real project need.
> doc: simple xfs with options

- README.md
- docs/table-to-gpt.md
- example/boot-raid1.nix
- example/gpt-name-with-whitespace.nix
- example/gpt-unformatted.nix
- example/legacy-table-with-whitespace.nix
- example/legacy-table.nix
- example/luks-on-mdadm.nix
- example/lvm-raid.nix
Most of the examples already have it, but not all of them and I already ran into this problem multiple times when copying example configs.
> fix: Apply umask=0077 to /boot partition in all examples

- lib/make-disk-image.nix
Function application has higher precedence than the // operator in Nix, so override is called on the main attrset before //, and the derivation does not reflect the customQemu value.
> make-disk-image: fix function precedence breaks customQemu

- example/zfs.nix
- lib/types/zfs_volume.nix
The `_unmount` attribute for `zfs_volume`s fails to evaluate if `content` is `null`; line 91 is missing a `or {}` at the end:
https://github.com/nix-community/disko/blob/f720e64ec37fa16ebba6354eadf310f81555cc07/lib/types/zfs_volume.nix#L82-L93
This PR fixes that. 
It also adds a no-content zfs volume to `example/zfs.nix` as a step towards testing for this issue, but the `_unmount` attribute is not yet evaluated as part of the tests. I am not sure what's a good way to include that evaluation in the tests. I ran into the issue while evaluating `system.build.installTest`; making sure this evaluates for all the test machines sounds reasonable to me, but I haven't added it to keep this fix small and straight-forward.
Breaking commit form git blame: d8f3cfc582356736eac3c46164cfc11a31aa082b
> fix eval of `zfs_volume`'s `_unmount` if `content` is `null`

- lib/make-disk-image.nix
nixpkgs removed kernelPackages.zfs with following error:
```
error: linuxPackages.zfs has been removed, use zfs_* instead, or linuxPackages.${pkgs.zfs.kernelModuleAttribute}
```
related to #959, but I don't understand the reason to hard-code the version.
> fix: use zfs kernel module which corresponds to user-space tools version in make-disk-image.nix

- lib/make-disk-image.nix
This PR fixes missing stdenv and broken virtiofs in the build script. 
Closes #957
> make-disk-image: fix image script stdenv and virtiofs

- lib/default.nix
Relating to issues discussed int #961 
I think I discovered another bug. I fixed the issue by renaming my type to "dxcachefs" instead of "bcachefs" In the dependency sort list, if there are any types that are alphabetically before the "disk" type, the sortDeviceDependencies function drops those at the top. So my pool object was getting collated as the very first entry in the _create functions. I don't think this was caught because mraid and zpool always appear at the end of the device dependency list due to their position in the alphabet. I think the function will need a specific check to always put disk device types at the beginning of the list.
Feedback on if there is another intended way to track type dependencies.
```nix
sorted = lib.sortDevicesByDependencies …
```
> Fix: Device dependencies not sorting correctly

- lib/default.nix
This reverts commit 40da43e8e5620505b9c8aacc4f0d7577ad1aff73.
> Revert "Fix: Device dependencies not sorting correctly"

- example/complex.nix
- lib/types/gpt.nix
- tests/complex.nix
Closes #948. This is my first ever Nix-related PR, so I'd appreciate feedback if you have any!
I wasn't sure if mdadm does expose `partuuid`, I assumed that it did but that may be wrong. I did run the tests, but I wasn't sure if it was wise to include UUIDs in example files. It's probably not a good idea for users to copy the UUID, they should generate their own.
> Add configration option for partition UUIDs

- lib/default.nix
I'm trying to run the command below, and getting an error because of shellcheck warning. 
`nix run github:nix-community/nixos-anywhere -- --flake '.#vm' --vm-test --ssh-port 5555`
```
error: builder for '/nix/store/yy4zrf91sqq29z6crnrqqljwi5977n0y-disko-destroy-format-mount.drv' failed with exit code 1;
last 7 log lines:
>
> In /nix/store/pljg8ral2skimva71gmfp2gh0w5w3sk6-disko-destroy-format-mount line 25:
> for dev in '/dev/vdb'; do
>            ^--------^ SC2041 (warning): This is a literal string. To run as a command, use $(..) instead of '..' . 
>
> For more information:
>   https://www.shellcheck.net/wiki/SC2041 -- This is a literal string. To run ...
For full logs, run 'nix log /nix/store/yy4zrf91sqq29z6crnrqqljwi5977n0y-disko-destroy-format-mount.drv'.
```
This was previously being …
> fix schellcheck warning failing build

- lib/make-disk-image.nix
Currently if building an image using cross compilation:
```
nixpkgs = {
config.allowUnsupportedSystem = true;
hostPlatform = "armv7l-linux";
buildPlatform = "x86_64-linux";
};
```
And resetting the Disko packages for binFmt use:
```
disko.imageBuilder =
let
diskoPkgs = nixpkgs.legacyPackages."x86_64-linux";
in
{
enableBinfmt = true;
pkgs = diskoPkgs;
kernelPackages = diskoPkgs.linuxPackages_latest;
};
```
Something will differ between host/build Platform in diskoPkgs (Not sure what, they look the same when tracing but there is functions that maybe differ) causing it to miss the nixpkgs cache and rebuilding for x86_64-linux. Also resettings buildPlatform fixes this.
> Set `buildPlatform` in make-disk-image

- disk-deactivate/disk-deactivate
- disk-deactivate/zfs-swap-deactivate.jq
- flake.nix
- package.nix
We will probably never support native formatting but this is useful when installing NixOS machines and printing formatting script.
> enable basic macos support

- lib/make-disk-image.nix
- lib/types/gpt.nix
- lib/types/mdadm.nix
- lib/types/table.nix
- lib/types/zfs_volume.nix
there are cases where this can just indefinitly hang as we can see in VM
tests. Let's add a tie breaker.
> udevadm settle: use timeout

- example/bcachefs.nix
- lib/default.nix
- lib/types/bcachefs.nix
- lib/types/bcachefs_filesystem.nix
- lib/types/table.nix
- tests/bcachefs.nix
This PR attempts to improve support for bcachefs, by implementing the following features:
> Improve support for bcachefs

- cli.nix
I've run into some problems with `disko` and should be seeing this error message.
But the message is hidden inside the nix store as it currently only outputs
```
/nix/store/2v3y6n08brldbjsrlhv3dzlj6vsknwv1-disko-compat-error/bin/disko-compat-error: line 8: unexpected EOF while looking for matching `''
error: builder for '/nix/store/q0ki67hbi78sqch9d2k0xg18imbf75gk-disko-compat-error.drv' failed with exit code 2
```
> [fix] added missing single quote in script

- .gitignore
- example/bcachefs.nix
- lib/types/bcachefs_filesystem.nix
- tests/bcachefs.nix
@Mic92 I manually tested our earlier commit and it seems like boot-time mounting of subvolumes actually was working, contrary to what I previously thought. The issue was that the automated test actually needed to unlock each of the mounted subvolumes individually (I didn't realise the boot process presented unlock prompts for each subvolume to be mounted, so the test was only unlocking the first one), which I've now amended with this new commit.
The OCR for the unlock prompts in the automated test seem to take a while though (and also causes my laptop's fans to spin like crazy), so hopefully it doesn't cause any timeouts in the CI.
> Make bcachefs subvolumes boot-time mount tests pass + add more bcachefs tests

- example/bcachefs.nix
- lib/types/bcachefs_filesystem.nix
- tests/bcachefs.nix
Addresses: https://github.com/koverstreet/bcachefs/issues/812
Ran into this issue, adding the full path seems to mitigate for the time being.
@nothingnesses
> bcachefs: fix ENOENT during boot

- lib/types/bcachefs.nix
- tests/bcachefs.nix
fixes device groups, for example where the disko config given looks like:
`label = "fast.dev1";`
after formatting, the device has a literal label of "fast.dev1" which breaks bcachefs device groups:
`echo fast > /sys/fs/bcachefs/<id>/options/foreground_target`
gives the error Invalid argument, echo fast.dev1 fails as well
`echo "\"fast\""` fails the same, however `echo "\"fast.dev1\""` succeeds
after this, device labels and groups work as expected and any component of the label can be used for a *_target
1 device's label was set with the disko config `label = "fast.dev1";`
1 set with `extraFormatArgs = [  "--label=fast.dev2" ];`
output from `bcachefs fs usage /`
`"fast.dev1" (device 3):         sda1              rw`
`fast.dev2 (device 4):           sdf1              rw`
setting devices as …
> remove quotes from --label creation for bcachefs

- lib/default.nix
Currently `subtype` suffers from a few issues:
1. If the definition is broken up, it mistakenly thinks [a partial definition is invalid](https://github.com/NixOS/nixpkgs/pull/254790/files#r1358073458).
2. Only the last partial definition is used.
This PR addresses them.
> allow subtype definitions to be broken up

- disko-install
- lib/make-disk-image.nix
- package.nix
Depends on https://github.com/NixOS/nixpkgs/pull/362081
> test build time with xcp
